import { useEffect, useState } from 'react';
import { Plus, Search, ExternalLink, Pencil, Trash2, MessageCircle, Check, X } from 'lucide-react';
import { api, assetUrl, date, money, whatsapp } from '../api';
import { useAuth } from '../auth';
import { Alert, Badge, Empty, Modal, PageTitle, Pagination } from '../components';

const blank={site_name:'',supervisor_name:'',mobile:'',expense_type:'',amount:'',expense_date:'',remarks:''};
export default function Expenses(){
 const {user}=useAuth();const [records,setRecords]=useState([]);const [pagination,setPagination]=useState();const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [editing,setEditing]=useState(null);const [error,setError]=useState('');
 const load=()=>api.get('/expenses',{params:{page,search,status}}).then(r=>{setRecords(r.data.data);setPagination(r.data.pagination)}).catch(e=>setError(e.response?.data?.message));
 useEffect(load,[page,search,status]);const save=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{editing?.id?await api.put(`/expenses/${editing.id}`,fd):await api.post('/expenses',fd);setEditing(null);load()}catch(e){setError(e.response?.data?.message||'Unable to save')}};
 const setState=async(id,status)=>{await api.patch(`/expenses/${id}/status`,{status});load()};const remove=async id=>{if(confirm('Delete this expense?')){await api.delete(`/expenses/${id}`);load()}};
 const remind=x=>whatsapp(x.mobile,`Dear ${x.supervisor_name},\n\nExpense bill for ${x.site_name} is pending.\n\nPlease upload the bill for approval.\n\nRegards,\nAccounts Team`);
 return <><PageTitle title="Site Expenses" subtitle="Capture bills and manage expense approvals." action={user.role!=='accounts'&&<button className="btn-primary" onClick={()=>setEditing(blank)}><Plus size={17}/> Add expense</button>}/><Alert message={error}/><div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input className="field pl-9" placeholder="Search site, supervisor, type..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="field sm:w-48" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Pending</option><option>Approved</option><option>Rejected</option></select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Site','Supervisor','Type','Amount','Date','Bill','Status','Actions'].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{records.map(x=><tr key={x.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-semibold">{x.site_name}</td><td className="px-4 py-3">{x.supervisor_name}</td><td className="px-4 py-3">{x.expense_type}</td><td className="px-4 py-3 font-semibold">{money(x.amount)}</td><td className="px-4 py-3">{date(x.expense_date)}</td><td className="px-4 py-3">{x.bill_pdf?<a target="_blank" className="text-blue-600" href={assetUrl(x.bill_pdf)}><ExternalLink size={17}/></a>:'—'}</td><td className="px-4 py-3"><Badge>{x.status}</Badge></td><td className="px-4 py-3"><div className="flex gap-1"><a className="btn-secondary !p-2 text-emerald-600" href={remind(x)} target="_blank"><MessageCircle size={16}/></a>{user.role!=='accounts'&&<button className="btn-secondary !p-2" onClick={()=>setEditing(x)}><Pencil size={16}/></button>}{user.role!=='supervisor'&&<><button title="Approve" className="btn-secondary !p-2 text-emerald-600" onClick={()=>setState(x.id,'Approved')}><Check size={16}/></button><button title="Reject" className="btn-secondary !p-2 text-red-600" onClick={()=>setState(x.id,'Rejected')}><X size={16}/></button></>}{user.role==='admin'&&<button className="btn-secondary !p-2 text-red-600" onClick={()=>remove(x.id)}><Trash2 size={16}/></button>}</div></td></tr>)}</tbody></table>{!records.length&&<Empty/>}</div><Pagination info={pagination} setPage={setPage}/></div>{editing&&<Modal title={editing.id?'Edit Site Expense':'Add Site Expense'} onClose={()=>setEditing(null)}><ExpenseForm data={editing} save={save}/></Modal>}</>;
}
function ExpenseForm({data,save}){const fields=[['site_name','Site Name','text'],['supervisor_name','Supervisor Name','text'],['mobile','Mobile','tel'],['expense_type','Expense Type','text'],['amount','Amount','number'],['expense_date','Expense Date','date']];return <form onSubmit={save} className="p-5"><div className="grid gap-4 sm:grid-cols-2">{fields.map(([n,l,t])=><label key={n}><span className="label">{l}</span><input className="field" required name={n} type={t} step={t==='number'?'0.01':undefined} defaultValue={data[n]?.slice?.(0,10)||data[n]||''}/></label>)}</div><label className="mt-4 block"><span className="label">Bill (PDF/JPG/PNG)</span><input className="field" name="bill" type="file" accept=".pdf,.jpg,.jpeg,.png"/></label><label className="mt-4 block"><span className="label">Remarks</span><textarea className="field" name="remarks" defaultValue={data.remarks||''}/></label><div className="mt-5 flex justify-end"><button className="btn-primary">Save Expense</button></div></form>}

