import { useEffect, useState } from 'react';
import { Plus, Search, ExternalLink, Pencil, Trash2, MessageCircle } from 'lucide-react';
import { api, assetUrl, date, money, whatsapp } from '../api';
import { useAuth } from '../auth';
import { Alert, Badge, Empty, Modal, PageTitle, Pagination } from '../components';

const blank = { supplier_name:'',mobile:'',invoice_no:'',gstin:'',amount:'',invoice_date:'',payment_date:'',utr_no:'',remarks:'' };
export default function Suppliers() {
  const { user } = useAuth(); const [records,setRecords]=useState([]); const [pagination,setPagination]=useState(); const [page,setPage]=useState(1); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [editing,setEditing]=useState(null); const [error,setError]=useState('');
<<<<<<< Updated upstream
  const load=()=>api.get('/suppliers',{params:{page,search,status}}).then(r=>{setRecords(r.data.data);setPagination(r.data.pagination)}).catch(e=>setError(e.response?.data?.message));
=======
  const load=()=>api.get('/suppliers',{params:{page,search,status}}).then(r=>{setRecords(Array.isArray(r.data?.data)?r.data.data:Array.isArray(r.data)?r.data:[]);setPagination(r.data?.pagination);setError('')}).catch(e=>{setRecords([]);setError(e.response?.data?.message||'Unable to load supplier payments')});
>>>>>>> Stashed changes
  useEffect(load,[page,search,status]);
  const save=async(e)=>{e.preventDefault();setError('');const fd=new FormData(e.currentTarget);try{editing?.id?await api.put(`/suppliers/${editing.id}`,fd):await api.post('/suppliers',fd);setEditing(null);load()}catch(e){setError(e.response?.data?.message||'Unable to save')}};
  const remove=async id=>{if(confirm('Delete this supplier payment?')){await api.delete(`/suppliers/${id}`);load()}};
  const remind=x=>whatsapp(x.mobile,`Dear ${x.supplier_name},\n\nGST Bill for Invoice ${x.invoice_no} is pending.\n\nPlease share GST bill to process payment.\n\nRegards,\nAccounts Team`);
  return <><PageTitle title="Supplier Payments" subtitle="Track invoices, GST bills, and payment details." action={<button className="btn-primary" onClick={()=>setEditing(blank)}><Plus size={17}/> Add payment</button>}/><Alert message={error}/><div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input className="field pl-9" placeholder="Search supplier, invoice, GSTIN..." value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}}/></div><select className="field sm:w-48" value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}}><option value="">All statuses</option><option>GST Pending</option><option>GST Uploaded</option></select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Supplier','Invoice','GSTIN','Amount','Invoice Date','GST Bill','Status','Actions'].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{records.map(x=><tr key={x.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-semibold">{x.supplier_name}</td><td className="px-4 py-3">{x.invoice_no}</td><td className="px-4 py-3">{x.gstin||'—'}</td><td className="px-4 py-3 font-semibold">{money(x.amount)}</td><td className="px-4 py-3">{date(x.invoice_date)}</td><td className="px-4 py-3">{x.gst_bill_pdf?<a className="text-blue-600" target="_blank" href={assetUrl(x.gst_bill_pdf)}><ExternalLink size={17}/></a>:'—'}</td><td className="px-4 py-3"><Badge>{x.status}</Badge></td><td className="px-4 py-3"><div className="flex gap-1"><a className="btn-secondary !p-2 text-emerald-600" href={remind(x)} target="_blank" title="WhatsApp reminder"><MessageCircle size={16}/></a><button className="btn-secondary !p-2" onClick={()=>setEditing(x)}><Pencil size={16}/></button>{user.role==='admin'&&<button className="btn-secondary !p-2 text-red-600" onClick={()=>remove(x.id)}><Trash2 size={16}/></button>}</div></td></tr>)}</tbody></table>{!records.length&&<Empty/>}</div><Pagination info={pagination} setPage={setPage}/></div>{editing&&<Modal title={editing.id?'Edit Supplier Payment':'Add Supplier Payment'} onClose={()=>setEditing(null)}><SupplierForm data={editing} save={save}/></Modal>}</>;
}
function SupplierForm({data,save}) { const fields=[['supplier_name','Supplier Name','text'],['mobile','Mobile','tel'],['invoice_no','Invoice Number','text'],['gstin','GSTIN','text'],['amount','Amount','number'],['invoice_date','Invoice Date','date'],['payment_date','Payment Date','date'],['utr_no','UTR Number','text']]; return <form onSubmit={save} className="p-5"><div className="grid gap-4 sm:grid-cols-2">{fields.map(([n,l,t])=><label key={n}><span className="label">{l}</span><input className="field" name={n} type={t} step={t==='number'?'0.01':undefined} required={['supplier_name','mobile','invoice_no','amount','invoice_date'].includes(n)} defaultValue={data[n]?.slice?.(0,10)||data[n]||''}/></label>)}</div><label className="mt-4 block"><span className="label">GST Bill (PDF/JPG/PNG)</span><input className="field" name="gst_bill" type="file" accept=".pdf,.jpg,.jpeg,.png"/></label><label className="mt-4 block"><span className="label">Remarks</span><textarea className="field" name="remarks" defaultValue={data.remarks||''}/></label><div className="mt-5 flex justify-end"><button className="btn-primary">Save Payment</button></div></form> }

